---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  labels:
    app: vault-agent-demo
data:
  config.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "app"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }
        "type" = "file"
      }
    }

    "exit_after_auth" = false
    "pid_file" = "/home/vault/.pid"

    "template" = {
      "contents" = "{{ with secret \"secret/hashiconf\" }}{{ .Data | toJSONPretty }}{{ end }}"
      "destination" = "/vault/secrets/kv-secret"
      "error_on_missing_key" = true
    }

    "vault" = {
      "address" = "https://vault.vault.svc.cluster.local:8200"
      "ca_cert" = "/vault/tls/ca.crt"
    }
  config-init.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "app"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }
        "type" = "file"
      }
    }

    "exit_after_auth" = true
    "pid_file" = "/home/vault/.pid"

    "template" = {
      "contents" = "{{ with secret \"secret/hashiconf\" }}{{ .Data| toJSONPretty }}{{ end }}"
      "destination" = "/vault/secrets/kv-secret"
      "error_on_missing_key" = true
    }

    "vault" = {
      "address" = "https://vault.vault.svc.cluster.local:8200"
      "ca_cert" = "/vault/tls/ca.crt"
    }
