---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: vault-agent-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-configmap: "agent-config"
        vault.hashicorp.com/tls-secret: "tls-test-client"
      labels:
        app: vault-agent-demo
    spec:
      shareProcessNamespace: true
      serviceAccountName: app
      containers:
      - name: app
        image: jodonnellhashi/static-secrets-app:1.0.0
        imagePullPolicy: Always
        securityContext:
          runAsUser: 100
          runAsGroup: 1000
        env:
        - name: APP_SECRET_PATH
          value: "/vault/secrets/kv-secret"
