---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      serviceAccountName: runner-sa
      containers:
      - name: github-runner
        image: jodonnellhashi/runner:1.0.0
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: runner-k8s-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
