name: Build
on:
  push:
    branches: [ main ]
#  push:
#    tags:
#      - '*'

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v2

#    - name: Set tag env
#      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}

    - name: Import Secrets
      uses: hashicorp/vault-action@v2.0.1
      with:
        url: https://vault.vault.svc.cluster.local:8200
        method: github
        githubToken: ${{ secrets.GH_TOKEN }}
        caCertificate: ${{ secrets.VAULT_CA }}
        secrets: |
          aws/creds/s3 access_key | AWS_ACCESS_KEY_ID;
          aws/creds/s3 secret_key | AWS_SECRET_ACCESS_KEY;

    - name: Sleeping because AWS IAM is eventually consistent ¯\_(ツ)_/¯
      run: sleep 10

    - name: App: compile linux amd64
      run: go build -a -o .build/pizza_${GOOS}_${GOARCH}
      env:
        GO111MODULE: on
        CGO_ENABLED: 0
        GOOS: linux
        GOARCH: amd64

    - name: App: compile darwin amd64
      run: go build -a -o .build/pizza_${GOOS}_${GOARCH}
      env:
        GO111MODULE: on
        CGO_ENABLED: 0
        GOOS: darwin
        GOARCH: amd64

    - name: Upload to S3
      run: |
        aws s3 sync .build/ s3://vault-action-demo
