name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v2

    - name: Import Secrets
      uses: hashicorp/vault-action@v2.0.1
      with:
        url: https://vault.vault.svc.cluster.local:8200
        method: github
        githubToken: ${{ secrets.GH_TOKEN }}
        caCertificate: ${{ secrets.VAULT_CA }}
        secrets: |
          aws/creds/s3 access_key | AWS_ACCESS_KEY_ID;
          aws/creds/s3 secret_key | AWS_SECRET_ACCESS_KEY;

    - name: Sleep
      run: sleep 10

    - name: Create Test File
      run: touch test.txt

    - name: Upload to S3
      run: |
        aws s3 cp test.txt --acl public-read s3://vault-action-demo/test.txt
