# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Import Secrets
      uses: hashicorp/vault-action@v2.0.1
      with:
        url: https://vault.vault.svc.cluster.local:8200
        method: github
        githubToken: ${{ secrets.GH_TOKEN }}
        caCertificate: ${{ secrets.VAULT_CA }}
        secrets: |
          aws/roles/s3 access_key | AWS_ACCESS_KEY_ID;
          aws/roles/s3 secret_key | AWS_SECRET_ACCESS_KEY;

    - name: Check env
      run: echo ${AWS_ACCESS_KEY_ID}
    - name: Check env
      run: echo ${AWS_SECRET_ACCESS_KEY}
