# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Import Secrets
      uses: hashicorp/vault-action@v2.0.1
      id: creds
      with:
        url: https://vault.vault.svc.cluster.local:8200
        method: github
        githubToken: ${{ secrets.GH_TOKEN }}
        caCertificate: ${{ secrets.VAULT_CA }}
        secrets: |
          aws/creds/s3 access_key | AWS_ACCESS_KEY_ID;
          aws/creds/s3 secret_key | AWS_SECRET_ACCESS_KEY;

    - name: Create Test File
      run: echo "Test" /tmp/test.txt

    - name: S3 Sync
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: "vault-action-demo"
        AWS_ACCESS_KEY_ID: ${{ steps.creds.outputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ steps.creds.outputs.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: '/tmp/test.txt'
